version: '3.8' 

services:
  redis:
    image:  redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:  
      - redis_data:/data  
    networks:  
      - redis-network 
  db:  
    image: postgres:latest  
    environment:  
      POSTGRES_DB: articles  
      POSTGRES_USER: denis  
      POSTGRES_PASSWORD: denis  
    ports:  
      - "5432:5432"  
    volumes:  
      - postgres_data_articles:/var/lib/postgresql/data  

volumes:  
  postgres_data_articles:
  redis_data:
  
networks:  
  redis-network: 